# Generated by Django 5.2.4 on 2025-07-30 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charger',
            name='link',
        ),
    ]
