# Generated by Django 5.2.4 on 2025-07-30 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0002_remove_charger_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Charger',
        ),
    ]
