# Generated by Django 5.2.4 on 2025-07-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_audiogear_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiogear',
            name='image',
            field=models.ImageField(upload_to='media/audio_gear_images/'),
        ),
    ]
