# Generated by Django 5.2.4 on 2025-07-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_charger'),
    ]

    operations = [
        migrations.CreateModel(
            name='phonecases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/phonecases/')),
            ],
        ),
    ]
